UPDATE product_product SET short_description = 'Light Pink -:- XL->Light Pink -:- 1X/2X' WHERE sku = '80067';
UPDATE product_product SET short_description = 'Red/Black -:- XL' WHERE sku = '80083';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80085';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL' WHERE sku = '80070';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- L' WHERE sku = '80038';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL->Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL->Red -:- S->Red -:- M->Red -:- L->Red -:- XL->White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80042';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80043';
UPDATE product_product SET short_description = 'Mint -:- S->Mint -:- M->Mint -:- L->Mint -:- XL->Light Pink -:- S->Light Pink -:- M->Light Pink -:- L->Light Pink -:- XL' WHERE sku = '80040';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L' WHERE sku = '80069';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80046';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80077';
UPDATE product_product SET short_description = 'Pink/Black -:- S->Pink/Black -:- M->Pink/Black -:- L->Pink/Black -:- XL->Yellow/Black -:- S->Yellow/Black -:- M->Yellow/Black -:- L->Yellow/Black -:- XL' WHERE sku = '80050';
UPDATE product_product SET short_description = 'Black -:- M' WHERE sku = '80048';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- L->Red -:- XL' WHERE sku = '80071';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80068';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M' WHERE sku = '80041';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL' WHERE sku = '80100';
UPDATE product_product SET short_description = 'Black/Pink -:- XL' WHERE sku = '80029';
UPDATE product_product SET short_description = 'White -:- M->White -:- L->White -:- XL' WHERE sku = '80049';
UPDATE product_product SET short_description = 'Red -:- 32' WHERE sku = '80081';
UPDATE product_product SET short_description = 'Rose Pink -:- S->Rose Pink -:- M->Rose Pink -:- L' WHERE sku = '80036';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80007';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL->Black -:- S->Black -:- M->Black -:- L->Black -:- XL->White -:- S' WHERE sku = '80003';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL->Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80055';
UPDATE product_product SET short_description = 'Black/Lavender -:- S' WHERE sku = '80091';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- L->Black -:- XL' WHERE sku = '80009';
UPDATE product_product SET short_description = 'Peach -:- M' WHERE sku = '80052';
UPDATE product_product SET short_description = 'Pink -:- 32->Pink -:- 34->Pink -:- 36->Pink -:- 38->Pink -:- XXLarge->Pink -:- XXXLarge' WHERE sku = '80051';
UPDATE product_product SET short_description = 'White -:- 32->White -:- 34->White -:- 36' WHERE sku = '80054';
UPDATE product_product SET short_description = 'Light Blue -:- XL' WHERE sku = '80057';
UPDATE product_product SET short_description = 'Red -:- 32/Small->Red -:- 34/Medium->Red -:- 36/Large->Red -:- XXLarge->Red -:- XXXLarge' WHERE sku = '80053';
UPDATE product_product SET short_description = 'Black/Gold -:- L' WHERE sku = '80056';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80015';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80011';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- L' WHERE sku = '80021';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80075';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80076';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80074';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80089';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL->Red -:- S->Red -:- M->Red -:- L->Red -:- XL->Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80045';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80044';
UPDATE product_product SET short_description = 'Pink -:- S' WHERE sku = '80039';
UPDATE product_product SET short_description = 'Champagne -:- L->Champagne -:- XL' WHERE sku = '80037';
UPDATE product_product SET short_description = 'White/Pink -:- XL' WHERE sku = '80097';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80030';
UPDATE product_product SET short_description = 'Black/White -:- S->Black/White -:- M->Black/White -:- L->Black/White -:- XL' WHERE sku = '80096';
UPDATE product_product SET short_description = 'Black/White -:- S/M->Black/White -:- M/L->Black/White -:- XL' WHERE sku = '80032';
UPDATE product_product SET short_description = 'White/Red -:- XL' WHERE sku = '80031';
UPDATE product_product SET short_description = 'Leopard -:- L' WHERE sku = '80078';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '60003';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL->Red -:- One Size->Red -:- XL->White -:- One Size->White -:- XL' WHERE sku = '60001';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL->Black -:- One Size' WHERE sku = '60002';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80064';
UPDATE product_product SET short_description = 'Mint -:- 3X/4X' WHERE sku = '80060';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- XL->Red -:- S->Red -:- XL' WHERE sku = '80065';
UPDATE product_product SET short_description = 'Black -:- S' WHERE sku = '80059';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '80062';
UPDATE product_product SET short_description = 'Black -:- S' WHERE sku = '80058';
UPDATE product_product SET short_description = 'White/Light Blue -:- S->White/Light Blue -:- M->White/Light Blue -:- L->White/Light Blue -:- XL' WHERE sku = '80063';
UPDATE product_product SET short_description = 'Pink -:- One Size->Pink -:- XL->Black -:- One Size->Black -:- XL->Red -:- One Size->Red -:- XL' WHERE sku = '80027';
UPDATE product_product SET short_description = 'White -:- 32->White -:- 38' WHERE sku = '80024';
UPDATE product_product SET short_description = 'Red -:- M' WHERE sku = '80061';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- L->Red -:- XL' WHERE sku = '80047';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80010';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL->Light Pink -:- S->Light Pink -:- M->Light Pink -:- L->Light Pink -:- XL->Black -:- S->Black -:- M->Black -:- L->Black -:- XL->White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80018';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80023';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80016';
UPDATE product_product SET short_description = 'Pink/Black -:- S->Pink/Black -:- M->Pink/Black -:- L->Pink/Black -:- XL->Red/Black -:- S->Red/Black -:- M->Red/Black -:- L->Red/Black -:- XL' WHERE sku = '80028';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80033';
UPDATE product_product SET short_description = 'Mint -:- S->Mint -:- L->Mint -:- XL' WHERE sku = '80034';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80099';
UPDATE product_product SET short_description = 'Pink/Black -:- S/M->Pink/Black -:- M/L->Pink/Black -:- XL' WHERE sku = '80013';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80072';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80001';
UPDATE product_product SET short_description = 'White/Pink/Red -:- XL' WHERE sku = '80079';
UPDATE product_product SET short_description = 'Light Blue -:- S->Light Blue -:- M->Light Blue -:- L->Light Blue -:- XL' WHERE sku = '80088';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80073';
UPDATE product_product SET short_description = 'White -:- S' WHERE sku = '80020';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80090';
UPDATE product_product SET short_description = 'Pink -:- One Size->Pink -:- XL' WHERE sku = '80017';
UPDATE product_product SET short_description = 'Red/White -:- XL' WHERE sku = '80012';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL' WHERE sku = '80006';
UPDATE product_product SET short_description = 'Pink -:- L' WHERE sku = '80014';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80035';
UPDATE product_product SET short_description = 'Black -:- XL->Red -:- XL->White -:- XL' WHERE sku = '70012';
UPDATE product_product SET short_description = 'Black/Lavender -:- XL' WHERE sku = '70030';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '70021';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '70018';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL->Red -:- One Size->Red -:- XL->Pink -:- One Size->Pink -:- XL' WHERE sku = '70022';
UPDATE product_product SET short_description = 'Pink -:- XL' WHERE sku = '70020';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL->Black -:- One Size->Black -:- XL->Yellow -:- One Size->Yellow -:- XL' WHERE sku = '70023';
UPDATE product_product SET short_description = 'Pink -:- XL' WHERE sku = '70002';
UPDATE product_product SET short_description = 'Lavender -:- XL' WHERE sku = '70032';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '70033';
UPDATE product_product SET short_description = 'Pink -:- XL' WHERE sku = '70031';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '70014';
UPDATE product_product SET short_description = 'Red/White -:- One Size->Red/White -:- XL' WHERE sku = '70005';
UPDATE product_product SET short_description = 'Green/White -:- XL' WHERE sku = '70015';
UPDATE product_product SET short_description = 'Yellow -:- XL' WHERE sku = '70004';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '70027';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL' WHERE sku = '70017';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '70019';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '70001';
UPDATE product_product SET short_description = 'Light Pink -:- M/L->Light Pink -:- XL' WHERE sku = '70026';
UPDATE product_product SET short_description = 'Fuchsia -:- XL' WHERE sku = '70035';
UPDATE product_product SET short_description = 'Red/White -:- XL' WHERE sku = '70013';
UPDATE product_product SET short_description = 'Burgundy/Black -:- XL' WHERE sku = '70006';
UPDATE product_product SET short_description = 'White -:- XL->Red -:- One Size->Red -:- XL->Black -:- One Size->Black -:- XL' WHERE sku = '70007';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL->Black -:- One Size->Pink -:- One Size->Pink -:- XL' WHERE sku = '70008';
UPDATE product_product SET short_description = 'Pink -:- XL->Black -:- One Size->Black -:- XL' WHERE sku = '70016';
UPDATE product_product SET short_description = 'Red/White -:- XL' WHERE sku = '70003';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '70009';
UPDATE product_product SET short_description = 'Red -:- XL->Pink -:- One Size->Pink -:- XL->White -:- One Size->White -:- XL' WHERE sku = '70010';
UPDATE product_product SET short_description = 'White -:- One Size' WHERE sku = '70036';
UPDATE product_product SET short_description = 'Fuchsia/Yellow -:- One Size->Fuchsia/Yellow -:- XL' WHERE sku = '70011';
UPDATE product_product SET short_description = 'Pink -:- XL' WHERE sku = '70025';
UPDATE product_product SET short_description = 'Pink -:- M/L->Pink -:- XL->Black -:- S/M->Black -:- M/L->Black -:- XL->Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '70024';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80019';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL->Pink -:- One Size->Pink -:- XL->Black -:- One Size->Black -:- XL' WHERE sku = '80022';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80080';
UPDATE product_product SET short_description = 'Black/Red -:- XL' WHERE sku = '80086';
UPDATE product_product SET short_description = 'Hot Pink -:- One Size->Hot Pink -:- XL' WHERE sku = '80084';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80095';
UPDATE product_product SET short_description = 'Rose Pink -:- S/M' WHERE sku = '80098';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '80005';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L' WHERE sku = '80002';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL->Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80004';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M' WHERE sku = '80008';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80117';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80121';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80124';
UPDATE product_product SET short_description = 'Red/Black -:- S/M->Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80128';
UPDATE product_product SET short_description = 'Black/Red -:- XL' WHERE sku = '80103';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80106';
UPDATE product_product SET short_description = 'White -:- M/L->White -:- XL' WHERE sku = '80119';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80125';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80126';
UPDATE product_product SET short_description = 'Beige/Red -:- One Size->Beige/Red -:- XL' WHERE sku = '80102';
UPDATE product_product SET short_description = 'White -:- M/L->White -:- XL' WHERE sku = '80105';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80107';
UPDATE product_product SET short_description = 'Red/Black -:- S/M->Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80110';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80111';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80112';
UPDATE product_product SET short_description = 'Ivory/Pink -:- XL' WHERE sku = '80113';
UPDATE product_product SET short_description = 'Red/Black -:- S->Red/Black -:- L->Red/Black -:- XL' WHERE sku = '80115';
UPDATE product_product SET short_description = 'Red/Black -:- S/M->Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80129';
UPDATE product_product SET short_description = 'Black/White -:- S/M->Black/White -:- M/L->Black/White -:- XL' WHERE sku = '80104';
UPDATE product_product SET short_description = 'Light Blue/White -:- S->Light Blue/White -:- M->Light Blue/White -:- L->Light Blue/White -:- XL' WHERE sku = '80108';
UPDATE product_product SET short_description = 'White/Red -:- One Size->White/Red -:- XL' WHERE sku = '80122';
UPDATE product_product SET short_description = 'Pink -:- XL' WHERE sku = '80127';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80161';
UPDATE product_product SET short_description = 'Aqua -:- One Size->Aqua -:- XL' WHERE sku = '80101';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80109';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80116';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '80130';
UPDATE product_product SET short_description = 'Black/Red -:- XL' WHERE sku = '80159';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80148';
UPDATE product_product SET short_description = 'White/Pink -:- S->White/Pink -:- M->White/Pink -:- L->White/Pink -:- XL' WHERE sku = '80160';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80114';
UPDATE product_product SET short_description = 'White/Black -:- S->White/Black -:- M->White/Black -:- L->White/Black -:- XL' WHERE sku = '80120';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL' WHERE sku = '80131';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80132';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80136';
UPDATE product_product SET short_description = 'Black/Light Blue -:- XL' WHERE sku = '80137';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '80139';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '80140';
UPDATE product_product SET short_description = 'White/Pink -:- S/M->White/Pink -:- M/L->White/Pink -:- XL' WHERE sku = '80142';
UPDATE product_product SET short_description = 'Baby Pink -:- S/M->Baby Pink -:- M/L->Baby Pink -:- XL' WHERE sku = '80151';
UPDATE product_product SET short_description = 'Grey -:- One Size->Grey -:- XL' WHERE sku = '80154';
UPDATE product_product SET short_description = 'Grey -:- XL' WHERE sku = '80155';
UPDATE product_product SET short_description = 'Multi Colors -:- One Size->Multi Colors -:- XL' WHERE sku = '80156';
UPDATE product_product SET short_description = 'White/Baby Pink -:- S/M->White/Baby Pink -:- M/L->White/Baby Pink -:- XL' WHERE sku = '80157';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80158';
UPDATE product_product SET short_description = 'Light Blue -:- XL' WHERE sku = '80162';
UPDATE product_product SET short_description = 'Black/Pink -:- XL' WHERE sku = '80165';
UPDATE product_product SET short_description = 'Aqua -:- S->Aqua -:- M->Aqua -:- L->Aqua -:- XL' WHERE sku = '80171';
UPDATE product_product SET short_description = 'Aqua -:- S->Aqua -:- L->Aqua -:- XL' WHERE sku = '80172';
UPDATE product_product SET short_description = 'Multi Color -:- S->Multi Color -:- M->Multi Color -:- L->Multi Color -:- XL' WHERE sku = '80164';
UPDATE product_product SET short_description = 'Peach -:- S->Peach -:- M->Peach -:- L->Peach -:- XL' WHERE sku = '80166';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80202';
UPDATE product_product SET short_description = 'Black/Green -:- M/L' WHERE sku = '80203';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80144';
UPDATE product_product SET short_description = 'Ivory -:- S/M->Ivory -:- M/L->Ivory -:- XL' WHERE sku = '80153';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- XL' WHERE sku = '80189';
UPDATE product_product SET short_description = 'White -:- L' WHERE sku = '80123';
UPDATE product_product SET short_description = 'Black/Fuchsia -:- XL' WHERE sku = '80118';
UPDATE product_product SET short_description = 'White -:- M/L->White -:- XL' WHERE sku = '80147';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80163';
UPDATE product_product SET short_description = 'Black/White -:- L->Black/White -:- XL' WHERE sku = '80167';
UPDATE product_product SET short_description = 'Aqua -:- S/M->Aqua -:- M/L->Aqua -:- XL' WHERE sku = '80168';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L' WHERE sku = '80169';
UPDATE product_product SET short_description = 'Pink/Yellow -:- XL' WHERE sku = '80170';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80175';
UPDATE product_product SET short_description = 'Red/Black -:- S/M->Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80176';
UPDATE product_product SET short_description = 'Black/White -:- S/M->Black/White -:- M/L->Black/White -:- XL' WHERE sku = '80178';
UPDATE product_product SET short_description = 'Peach -:- S->Peach -:- XL' WHERE sku = '80179';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80180';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80181';
UPDATE product_product SET short_description = 'Black/Red -:- One Size->Black/Red -:- XL' WHERE sku = '80152';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- XL' WHERE sku = '80201';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80133';
UPDATE product_product SET short_description = 'Multi Colors -:- S->Multi Colors -:- M->Multi Colors -:- L->Multi Colors -:- XL' WHERE sku = '80135';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80141';
UPDATE product_product SET short_description = 'Multi Colors -:- XL' WHERE sku = '80146';
UPDATE product_product SET short_description = 'Fuchsia -:- XL' WHERE sku = '80150';
UPDATE product_product SET short_description = 'Black/Pink -:- XL' WHERE sku = '80174';
UPDATE product_product SET short_description = 'Burgundy -:- S' WHERE sku = '80186';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80187';
UPDATE product_product SET short_description = 'Black -:- L' WHERE sku = '80190';
UPDATE product_product SET short_description = 'Black/Blue -:- S' WHERE sku = '80191';
UPDATE product_product SET short_description = 'White -:- XL' WHERE sku = '70037';
UPDATE product_product SET short_description = 'Black -:- S/M' WHERE sku = '80177';
UPDATE product_product SET short_description = 'Burgundy -:- XL' WHERE sku = '80183';
UPDATE product_product SET short_description = 'Blue/Aqua -:- L->Blue/Aqua -:- XL' WHERE sku = '80184';
UPDATE product_product SET short_description = 'Black/Blue -:- S->Black/Blue -:- XL' WHERE sku = '80185';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80188';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80182';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80192';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80193';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80194';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80195';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80196';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80197';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80198';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80199';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80200';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80134';
UPDATE product_product SET short_description = 'Brown -:- S->Brown -:- M->Brown -:- L->Brown -:- XL' WHERE sku = '80149';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80143';
UPDATE product_product SET short_description = 'Black -:- L->Black -:- XL' WHERE sku = '80145';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M' WHERE sku = '80138';
UPDATE product_product SET short_description = 'Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80245';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80246';
UPDATE product_product SET short_description = 'Black -:- S/M' WHERE sku = '80251';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L' WHERE sku = '80250';
UPDATE product_product SET short_description = 'Black/White -:- S/M' WHERE sku = '80242';
UPDATE product_product SET short_description = 'Black/White/Red -:- S->Black/White/Red -:- M->Black/White/Red -:- L->Black/White/Red -:- XL' WHERE sku = '80243';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L' WHERE sku = '80252';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL->Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80253';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L' WHERE sku = '80244';
UPDATE product_product SET short_description = 'Black/Red -:- S/M' WHERE sku = '80247';
UPDATE product_product SET short_description = 'Black -:- M/L' WHERE sku = '80248';
UPDATE product_product SET short_description = 'Pink -:- 34B->Pink -:- 34C->Pink -:- 36C->Pink -:- 36D' WHERE sku = '80257';
UPDATE product_product SET short_description = 'Black -:- S' WHERE sku = '80256';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80255';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80254';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80299';
UPDATE product_product SET short_description = 'Silver/Cherry Red -:- One Size' WHERE sku = '80300';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80301';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80302';
UPDATE product_product SET short_description = 'Silver/Red -:- One Size' WHERE sku = '80303';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80304';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80305';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80307';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80308';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80309';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80310';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80311';
UPDATE product_product SET short_description = 'Silver/Blue -:- One Size' WHERE sku = '80312';
UPDATE product_product SET short_description = 'Gold -:- One Size' WHERE sku = '80313';
UPDATE product_product SET short_description = 'Silver/Cherry Red -:- One Size' WHERE sku = '80314';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80315';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80316';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80317';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80318';
UPDATE product_product SET short_description = 'Pink -:- 34B->Pink -:- 34C->Pink -:- 36C->Pink -:- 36D' WHERE sku = '80274';
UPDATE product_product SET short_description = 'Nude -:- S->Nude -:- M->Nude -:- L->Nude -:- XL' WHERE sku = '80275';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80258';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- XL' WHERE sku = '80259';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL->White/Black -:- S->White/Black -:- M->White/Black -:- L->White/Black -:- XL' WHERE sku = '80260';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80261';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL->Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80262';
UPDATE product_product SET short_description = 'Red/Black -:- S->Red/Black -:- L->Red/Black -:- XL' WHERE sku = '80263';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL->Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80264';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80265';
UPDATE product_product SET short_description = 'Shades of Red and Purple -:- S/M->Shades of Red and Purple -:- M/L' WHERE sku = '80266';
UPDATE product_product SET short_description = 'White/Black -:- S->White/Black -:- M->White/Black -:- L->White/Black -:- XL' WHERE sku = '80267';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80268';
UPDATE product_product SET short_description = 'Black/White -:- XL' WHERE sku = '80269';
UPDATE product_product SET short_description = 'White/Black -:- M/L->White/Black -:- XL' WHERE sku = '80270';
UPDATE product_product SET short_description = 'White/Purple -:- S->White/Purple -:- L->White/Purple -:- XL' WHERE sku = '80271';
UPDATE product_product SET short_description = 'Floral White/Black Turquoise -:- S->Floral White/Black Turquoise -:- M->Floral White/Black Turquoise -:- L->Floral White/Black Turquoise -:- XL' WHERE sku = '80272';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80273';
UPDATE product_product SET short_description = 'Blue -:- S->Blue -:- M->Blue -:- L->Blue -:- XL' WHERE sku = '80276';
UPDATE product_product SET short_description = 'Black/Blue -:- M/L' WHERE sku = '80277';
UPDATE product_product SET short_description = 'Blue -:- L->Blue -:- XL' WHERE sku = '80278';
UPDATE product_product SET short_description = 'Black -:- XL->Red -:- XL' WHERE sku = '80279';
UPDATE product_product SET short_description = 'Hot Pink -:- S/M->Hot Pink -:- M/L->Hot Pink -:- XL' WHERE sku = '80280';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80281';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80282';
UPDATE product_product SET short_description = 'Deep Pink -:- S->Deep Pink -:- M->Deep Pink -:- L->Deep Pink -:- XL->White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80283';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80284';
UPDATE product_product SET short_description = 'Hot Pink -:- S/M->Hot Pink -:- M/L->Hot Pink -:- XL' WHERE sku = '80285';
UPDATE product_product SET short_description = 'Hot Pink -:- S/M->Hot Pink -:- M/L->Hot Pink -:- XL' WHERE sku = '80286';
UPDATE product_product SET short_description = 'Peru Brown -:- S/M->Peru Brown -:- M/L->Peru Brown -:- XL->Sky Blue -:- S/M->Sky Blue -:- M/L->Sky Blue -:- XL' WHERE sku = '80287';
UPDATE product_product SET short_description = 'Black/Hot Pink -:- S/M->Black/Hot Pink -:- M/L->Black/Sky Blue -:- S/M->Black/Sky Blue -:- M/L' WHERE sku = '80288';
UPDATE product_product SET short_description = 'Blue/Black -:- S' WHERE sku = '80289';
UPDATE product_product SET short_description = 'Deep Pink -:- S->Deep Pink -:- M->Deep Pink -:- L->Deep Pink -:- XL' WHERE sku = '80290';
UPDATE product_product SET short_description = 'Medium Violet Red/Black -:- M/L->Medium Violet Red/Black -:- XL' WHERE sku = '80291';
UPDATE product_product SET short_description = 'Black/Sky Blue -:- S/M->Black/Sky Blue -:- M/L->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80292';
UPDATE product_product SET short_description = 'Deep Pink -:- S/M->Deep Pink -:- XL->Sky Blue -:- S/M->Sky Blue -:- M/L->Sky Blue -:- XL' WHERE sku = '80293';
UPDATE product_product SET short_description = 'Black/Teal -:- S->Black/Teal -:- M->Black/Teal -:- L' WHERE sku = '80294';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80295';
UPDATE product_product SET short_description = 'Deep Pink -:- M' WHERE sku = '80296';
UPDATE product_product SET short_description = 'Deep Pink -:- S/M->Deep Pink -:- M/L->Deep Pink -:- XL->Sky Blue -:- S/M->Sky Blue -:- M/L->Sky Blue -:- XL' WHERE sku = '80297';
UPDATE product_product SET short_description = 'Hot Pink -:- M/L->Hot Pink -:- XL' WHERE sku = '80298';
UPDATE product_product SET short_description = 'Silver -:- One Size' WHERE sku = '80306';
UPDATE product_product SET short_description = 'Multicolor -:- S/M->Multicolor -:- M/L->Multicolor -:- XL' WHERE sku = '80400';
UPDATE product_product SET short_description = 'Multicolor -:- S/M->Multicolor -:- M/L->Multicolor -:- XL' WHERE sku = '80401';
UPDATE product_product SET short_description = 'Multicolor -:- S/M->Multicolor -:- M/L->Multicolor -:- XL' WHERE sku = '80402';
UPDATE product_product SET short_description = 'Multicolor -:- S/M->Multicolor -:- M/L->Multicolor -:- XL' WHERE sku = '80403';
UPDATE product_product SET short_description = 'Blue -:- S->Blue -:- M->Blue -:- XL' WHERE sku = '80405';
UPDATE product_product SET short_description = 'Pink/Red -:- S->Pink/Red -:- M->Pink/Red -:- L->Pink/Red -:- XL' WHERE sku = '80406';
UPDATE product_product SET short_description = 'Pink/Yellow -:- S->Pink/Yellow -:- M->Pink/Yellow -:- L->Pink/Yellow -:- XL' WHERE sku = '80407';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80408';
UPDATE product_product SET short_description = 'Light Pink -:- S/M->Light Pink -:- M/L->Light Pink -:- XL' WHERE sku = '80409';
UPDATE product_product SET short_description = 'Medium Orchid -:- M' WHERE sku = '80410';
UPDATE product_product SET short_description = 'Light Pink -:- One Size->Light Pink -:- XL' WHERE sku = '80411';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80413';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80412';
UPDATE product_product SET short_description = 'Shades of Pink and Brown -:- S/M->Shades of Pink and Brown -:- M/L->Shades of Pink and Brown -:- XL' WHERE sku = '80414';
UPDATE product_product SET short_description = 'Red -:- XL' WHERE sku = '80415';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80416';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M' WHERE sku = '80417';
UPDATE product_product SET short_description = 'Black -:- S' WHERE sku = '80420';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80421';
UPDATE product_product SET short_description = 'Lavender -:- S->Lavender -:- M->Lavender -:- L->Lavender -:- XL' WHERE sku = '80422';
UPDATE product_product SET short_description = 'Medium Blue -:- S->Medium Blue -:- M->Medium Blue -:- XL' WHERE sku = '80423';
UPDATE product_product SET short_description = 'Light Blue -:- S->Light Blue -:- M->Light Blue -:- L->Light Blue -:- XL' WHERE sku = '80424';
UPDATE product_product SET short_description = 'Wheat Yellow -:- S->Wheat Yellow -:- M->Wheat Yellow -:- L->Wheat Yellow -:- XL' WHERE sku = '80425';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80427';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- L' WHERE sku = '80429';
UPDATE product_product SET short_description = 'Red/Black -:- S->Red/Black -:- M->Red/Black -:- XL' WHERE sku = '80430';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80433';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80439';
UPDATE product_product SET short_description = 'Hot Pink/Black -:- S->Hot Pink/Black -:- M->Hot Pink/Black -:- L->Hot Pink/Black -:- XL' WHERE sku = '80443';
UPDATE product_product SET short_description = 'Black/Blue -:- S->Black/Blue -:- M' WHERE sku = '80444';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80442';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80418';
UPDATE product_product SET short_description = 'Hot Pink -:- S->Hot Pink -:- M->Hot Pink -:- L' WHERE sku = '80428';
UPDATE product_product SET short_description = 'Black -:- S' WHERE sku = '80438';
UPDATE product_product SET short_description = 'Light Pink/Black Trim -:- M/L->Light Pink/Black Trim -:- XL' WHERE sku = '80447';
UPDATE product_product SET short_description = 'Black/Pink Lace -:- S/M->Black/Pink Lace -:- M/L->Black/Pink Lace -:- XL' WHERE sku = '80452';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80466';
UPDATE product_product SET short_description = 'Black/Pink -:- M/L' WHERE sku = '80473';
UPDATE product_product SET short_description = 'Light Apple Green -:- S/M->Light Apple Green -:- M/L->Light Apple Green -:- XL' WHERE sku = '80479';
UPDATE product_product SET short_description = 'Pink/Black -:- S->Pink/Black -:- M->Pink/Black -:- L->Pink/Black -:- XL' WHERE sku = '80483';
UPDATE product_product SET short_description = 'White/Pink -:- M/L' WHERE sku = '80490';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80505';
UPDATE product_product SET short_description = 'Soft Pink -:- S->Soft Pink -:- M->Soft Pink -:- L->Soft Pink -:- XL' WHERE sku = '80545';
UPDATE product_product SET short_description = 'White -:- M/L' WHERE sku = '80595';
UPDATE product_product SET short_description = 'Satin Blue -:- S->Satin Blue -:- M->Satin Blue -:- L->Satin Blue -:- XL' WHERE sku = '80596';
UPDATE product_product SET short_description = 'White/Leopard -:- S/M->White/Leopard -:- M/L->White/Leopard -:- XL' WHERE sku = '80604';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- XL' WHERE sku = '80609';
UPDATE product_product SET short_description = 'Leopard/Black -:- One Size->Leopard/Black -:- XL' WHERE sku = '80449';
UPDATE product_product SET short_description = 'Black/White -:- One Size->Black/White -:- XL' WHERE sku = '80602';
UPDATE product_product SET short_description = 'Brown Camouflage -:- S/M->Brown Camouflage -:- M/L->Brown Camouflage -:- XL' WHERE sku = '80465';
UPDATE product_product SET short_description = 'Satin Blue -:- S/M->Satin Blue -:- M/L->Satin Blue -:- XL' WHERE sku = '80601';
UPDATE product_product SET short_description = 'Brown Camouflage -:- S/M->Brown Camouflage -:- M/L->Brown Camouflage -:- XL' WHERE sku = '80467';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80489';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80589';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80590';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80592';
UPDATE product_product SET short_description = 'Leopard -:- One Size->Leopard -:- XL' WHERE sku = '80600';
UPDATE product_product SET short_description = 'Camouflage -:- M/L->Camouflage -:- XL' WHERE sku = '80610';
UPDATE product_product SET short_description = 'Lipstick Pink -:- S/M' WHERE sku = '80468';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80496';
UPDATE product_product SET short_description = 'Black/White -:- One Size->Black/White -:- XL' WHERE sku = '80498';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L' WHERE sku = '80501';
UPDATE product_product SET short_description = 'White -:- M/L->White -:- XL' WHERE sku = '80510';
UPDATE product_product SET short_description = 'Baby Pink -:- M/L->Baby Pink -:- XL' WHERE sku = '80511';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80512';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80593';
UPDATE product_product SET short_description = 'Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80474';
UPDATE product_product SET short_description = 'Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80497';
UPDATE product_product SET short_description = 'Red Wine -:- S/M->Red Wine -:- M/L->Red Wine -:- XL->Pink -:- S/M->Pink -:- M/L->Pink -:- XL->Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80499';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80581';
UPDATE product_product SET short_description = 'Blue/Brown -:- S->Blue/Brown -:- M->Blue/Brown -:- L->Blue/Brown -:- XL' WHERE sku = '80598';
UPDATE product_product SET short_description = 'Black/Hot Pink -:- S/M->Black/Hot Pink -:- M/L->Black/Hot Pink -:- XL' WHERE sku = '80587';
UPDATE product_product SET short_description = 'Black/Blue Embroidery -:- S/M->Black/Blue Embroidery -:- M/L->Black/Blue Embroidery -:- XL' WHERE sku = '80457';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80464';
UPDATE product_product SET short_description = 'Rose/Black -:- S/M->Rose/Black -:- M/L' WHERE sku = '80482';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80580';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- XL' WHERE sku = '80448';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80455';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80475';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80476';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80502';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80509';
UPDATE product_product SET short_description = 'Black/Green -:- S->Black/Green -:- M->Black/Green -:- L->Black/Green -:- XL' WHERE sku = '80459';
UPDATE product_product SET short_description = 'Red/Black -:- S' WHERE sku = '80462';
UPDATE product_product SET short_description = 'Grape -:- S->Grape -:- M' WHERE sku = '80488';
UPDATE product_product SET short_description = 'Satin Baby Blue -:- S->Satin Baby Blue -:- M->Satin Baby Blue -:- L->Satin Baby Blue -:- XL' WHERE sku = '80507';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L' WHERE sku = '80508';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80469';
UPDATE product_product SET short_description = 'Ivory -:- S->Ivory -:- XL' WHERE sku = '80471';
UPDATE product_product SET short_description = 'Rose/Ivory -:- S' WHERE sku = '80500';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80485';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80445';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80446';
UPDATE product_product SET short_description = 'Sea Blue -:- S->Sea Blue -:- M->Sea Blue -:- L->Sea Blue -:- XL->Sea Blue -:- 3X' WHERE sku = '80451';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L' WHERE sku = '80453';
UPDATE product_product SET short_description = 'Red Plaid -:- S' WHERE sku = '80454';
UPDATE product_product SET short_description = 'Red Wine/Black -:- S' WHERE sku = '80456';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80460';
UPDATE product_product SET short_description = 'Black -:- XL' WHERE sku = '80461';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80463';
UPDATE product_product SET short_description = 'Black/Blue -:- XL' WHERE sku = '80477';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80480';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- 1X->Red -:- 2X->Red -:- 3X' WHERE sku = '80487';
UPDATE product_product SET short_description = 'Black/Nude -:- S/M->Black/Nude -:- M/L->Black/Nude -:- XL' WHERE sku = '80491';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80492';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- 1X->Red -:- 2X->Red -:- 3X' WHERE sku = '80493';
UPDATE product_product SET short_description = 'Soft Pink -:- S/M->Soft Pink -:- M/L->Soft Pink -:- XL' WHERE sku = '80494';
UPDATE product_product SET short_description = 'Red -:- One Size->Red -:- XL' WHERE sku = '80495';
UPDATE product_product SET short_description = 'Pink/Black -:- S/M->Pink/Black -:- M/L->Pink/Black -:- XL' WHERE sku = '80503';
UPDATE product_product SET short_description = 'Soft Pink -:- S/M->Soft Pink -:- M/L->Soft Pink -:- XL' WHERE sku = '80504';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80513';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80522';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80525';
UPDATE product_product SET short_description = 'Black/White -:- S/M->Black/White -:- M/L->Black/White -:- XL' WHERE sku = '80526';
UPDATE product_product SET short_description = 'Black -:- M/L' WHERE sku = '80530';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80532';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80537';
UPDATE product_product SET short_description = 'Purple/Black -:- S/M->Purple/Black -:- M/L' WHERE sku = '80551';
UPDATE product_product SET short_description = 'Soft Pink -:- S/M->Soft Pink -:- M/L->Soft Pink -:- XL' WHERE sku = '80554';
UPDATE product_product SET short_description = 'Soft Pink -:- S/M->Soft Pink -:- M/L->Soft Pink -:- XL' WHERE sku = '80555';
UPDATE product_product SET short_description = 'Soft Pink -:- XL' WHERE sku = '80557';
UPDATE product_product SET short_description = 'Floral -:- S/M->Floral -:- M/L->Floral -:- XL' WHERE sku = '80559';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- XL' WHERE sku = '80560';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L' WHERE sku = '80564';
UPDATE product_product SET short_description = 'Purple/Satin Pink -:- One Size->Purple/Satin Pink -:- XL' WHERE sku = '80565';
UPDATE product_product SET short_description = 'Black/Purple -:- S/M->Black/Purple -:- M/L->Black/Purple -:- XL' WHERE sku = '80569';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80572';
UPDATE product_product SET short_description = 'Red/Black -:- S/M->Red/Black -:- M/L->Red/Black -:- XL' WHERE sku = '80573';
UPDATE product_product SET short_description = 'Black/Cherry Print -:- S/M->Black/Cherry Print -:- M/L->Black/Cherry Print -:- XL' WHERE sku = '80579';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80594';
UPDATE product_product SET short_description = 'Black/White -:- One Size->Black/White -:- XL' WHERE sku = '80606';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80612';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80613';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80617';
UPDATE product_product SET short_description = 'Light Pink/Black -:- S/M->Light Pink/Black -:- M/L->Light Pink/Black -:- XL' WHERE sku = '80329';
UPDATE product_product SET short_description = 'Light Pink/Black -:- S/M->Light Pink/Black -:- M/L->Light Pink/Black -:- XL' WHERE sku = '80330';
UPDATE product_product SET short_description = 'Light Pink/Black -:- M/L->Light Pink/Black -:- XL' WHERE sku = '80331';
UPDATE product_product SET short_description = 'Light Pink/Black -:- S->Light Pink/Black -:- M->Light Pink/Black -:- L->Light Pink/Black -:- XL' WHERE sku = '80332';
UPDATE product_product SET short_description = 'Light Sky Blue -:- S/M->Light Sky Blue -:- M/L->Light Sky Blue -:- XL' WHERE sku = '80336';
UPDATE product_product SET short_description = 'Light Sky Blue -:- S/M->Light Sky Blue -:- M/L->Light Sky Blue -:- XL' WHERE sku = '80337';
UPDATE product_product SET short_description = 'Light Sky Blue -:- S->Light Sky Blue -:- M->Light Sky Blue -:- L->Light Sky Blue -:- XL' WHERE sku = '80338';
UPDATE product_product SET short_description = 'Light Sky Blue -:- S/M->Light Sky Blue -:- M/L->Light Sky Blue -:- XL' WHERE sku = '80339';
UPDATE product_product SET short_description = 'Light Sky Blue -:- S/M->Light Sky Blue -:- M/L->Light Sky Blue -:- XL' WHERE sku = '80340';
UPDATE product_product SET short_description = 'Plum -:- S->Plum -:- M->Plum -:- L->Plum -:- XL' WHERE sku = '80341';
UPDATE product_product SET short_description = 'Plum -:- S/M->Plum -:- M/L->Plum -:- XL' WHERE sku = '80342';
UPDATE product_product SET short_description = 'Plum -:- M/L->Plum -:- XL' WHERE sku = '80343';
UPDATE product_product SET short_description = 'Plum -:- S/M->Plum -:- M/L->Plum -:- XL' WHERE sku = '80344';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80352';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80353';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80354';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80355';
UPDATE product_product SET short_description = 'Medium Violet Red/Black -:- S->Medium Violet Red/Black -:- M->Medium Violet Red/Black -:- L->Medium Violet Red/Black -:- XL' WHERE sku = '80374';
UPDATE product_product SET short_description = 'Medium Violet Red/Black -:- S/M->Medium Violet Red/Black -:- M/L->Medium Violet Red/Black -:- XL' WHERE sku = '80375';
UPDATE product_product SET short_description = 'Medium Violet Red/Black -:- XL' WHERE sku = '80376';
UPDATE product_product SET short_description = 'Medium Violet Red/Black -:- S/M->Medium Violet Red/Black -:- M/L->Medium Violet Red/Black -:- XL' WHERE sku = '80377';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- XL' WHERE sku = '80382';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL' WHERE sku = '80616';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80441';
UPDATE product_product SET short_description = 'Black/Pink -:- S/M->Black/Pink -:- M/L->Black/Pink -:- XL' WHERE sku = '80458';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L' WHERE sku = '80470';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80472';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80481';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80484';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- XL' WHERE sku = '80486';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80506';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80516';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80520';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80521';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80523';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80524';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80528';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80529';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80533';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80534';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80535';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80539';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80540';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80542';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80543';
UPDATE product_product SET short_description = 'Hot Pink/Red -:- S->Hot Pink/Red -:- M->Hot Pink/Red -:- L->Hot Pink/Red -:- XL' WHERE sku = '80544';
UPDATE product_product SET short_description = 'Hot Pink -:- S->Hot Pink -:- M->Hot Pink -:- L->Hot Pink -:- XL' WHERE sku = '80546';
UPDATE product_product SET short_description = 'Pink/Yellow Strings -:- S->Pink/Yellow Strings -:- M->Pink/Yellow Strings -:- L->Pink/Yellow Strings -:- XL' WHERE sku = '80547';
UPDATE product_product SET short_description = 'Soft Pink/Black -:- S->Soft Pink/Black -:- M->Soft Pink/Black -:- L->Soft Pink/Black -:- XL' WHERE sku = '80548';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80549';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80550';
UPDATE product_product SET short_description = 'Soft Pink -:- S/M->Soft Pink -:- M/L->Soft Pink -:- XL' WHERE sku = '80552';
UPDATE product_product SET short_description = 'Pink -:- S->Pink -:- M->Pink -:- L->Pink -:- XL' WHERE sku = '80556';
UPDATE product_product SET short_description = 'Satin Pink -:- S->Satin Pink -:- M->Satin Pink -:- L->Satin Pink -:- XL' WHERE sku = '80558';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80561';
UPDATE product_product SET short_description = 'Lavender -:- S->Lavender -:- M->Lavender -:- L->Lavender -:- XL' WHERE sku = '80562';
UPDATE product_product SET short_description = 'Satin Blue/White -:- One Size->Satin Blue/White -:- XL' WHERE sku = '80563';
UPDATE product_product SET short_description = 'Satin Pink/Black -:- One Size->Satin Pink/Black -:- XL' WHERE sku = '80566';
UPDATE product_product SET short_description = 'Black/Blue -:- S/M->Black/Blue -:- M/L->Black/Blue -:- XL' WHERE sku = '80567';
UPDATE product_product SET short_description = 'Black/Red -:- S/M->Black/Red -:- M/L->Black/Red -:- XL' WHERE sku = '80571';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80574';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80575';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L' WHERE sku = '80578';
UPDATE product_product SET short_description = 'Pink/Black -:- S->Pink/Black -:- M->Pink/Black -:- L->Pink/Black -:- XL' WHERE sku = '80582';
UPDATE product_product SET short_description = 'Black -:- One Size->Black -:- XL' WHERE sku = '80583';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80588';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80591';
UPDATE product_product SET short_description = 'Light Mint Green -:- S->Light Mint Green -:- M->Light Mint Green -:- XL' WHERE sku = '80597';
UPDATE product_product SET short_description = 'Sweet Peach -:- S->Sweet Peach -:- M->Sweet Peach -:- L->Sweet Peach -:- XL' WHERE sku = '80599';
UPDATE product_product SET short_description = 'Sweet Sunshine -:- S->Sweet Sunshine -:- M->Sweet Sunshine -:- L->Sweet Sunshine -:- XL' WHERE sku = '80603';
UPDATE product_product SET short_description = 'Blue -:- S/M->Blue -:- M/L->Blue -:- XL' WHERE sku = '80605';
UPDATE product_product SET short_description = 'Camouflage -:- S/M->Camouflage -:- M/L->Camouflage -:- XL' WHERE sku = '80608';
UPDATE product_product SET short_description = 'Ivory White -:- S/M->Ivory White -:- M/L->Ivory White -:- XL' WHERE sku = '80614';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80615';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80618';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80620';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80622';
UPDATE product_product SET short_description = 'White Pink -:- S->White Pink -:- M->White Pink -:- L->White Pink -:- XL' WHERE sku = '80623';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80728';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80626';
UPDATE product_product SET short_description = 'White/Purple -:- S/M->White/Purple -:- M/L->White/Purple -:- XL' WHERE sku = '80627';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80628';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80632';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L' WHERE sku = '80633';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80635';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80646';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80647';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80649';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80658';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80660';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80668';
UPDATE product_product SET short_description = 'Red/Black -:- S->Red/Black -:- M->Red/Black -:- L->Red/Black -:- XL' WHERE sku = '80669';
UPDATE product_product SET short_description = 'Purple -:- S/M->Purple -:- M/L->Purple -:- XL' WHERE sku = '80670';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80671';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80672';
UPDATE product_product SET short_description = 'Black/Yellow -:- S/M->Black/Yellow -:- M/L->Black/Yellow -:- XL' WHERE sku = '80680';
UPDATE product_product SET short_description = 'Light Purple -:- S->Light Purple -:- M->Light Purple -:- L->Light Purple -:- XL' WHERE sku = '80681';
UPDATE product_product SET short_description = 'Light Purple/Black -:- S/M->Light Purple/Black -:- M/L->Light Purple/Black -:- XL' WHERE sku = '80683';
UPDATE product_product SET short_description = 'Purple/Pink -:- S->Purple/Pink -:- M->Purple/Pink -:- L->Purple/Pink -:- XL' WHERE sku = '80684';
UPDATE product_product SET short_description = 'Neutral/Leopard -:- S/M->Neutral/Leopard -:- M/L->Neutral/Leopard -:- XL' WHERE sku = '80686';
UPDATE product_product SET short_description = 'Leopard -:- S/M->Leopard -:- M/L->Leopard -:- XL' WHERE sku = '80689';
UPDATE product_product SET short_description = 'Pink/Black -:- S->Pink/Black -:- M->Pink/Black -:- L->Pink/Black -:- XL' WHERE sku = '80694';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80695';
UPDATE product_product SET short_description = 'Red -:- S->Red -:- M->Red -:- L->Red -:- XL' WHERE sku = '80696';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80697';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80706';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80707';
UPDATE product_product SET short_description = 'Black/Silver -:- S->Black/Silver -:- M->Black/Silver -:- L->Black/Silver -:- XL->Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80709';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80710';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80715';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80717';
UPDATE product_product SET short_description = 'Black/Silver -:- S->Black/Silver -:- M->Black/Silver -:- L->Black/Silver -:- XL->Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80722';
UPDATE product_product SET short_description = 'Black/Red -:- S->Black/Red -:- M->Black/Red -:- L->Black/Red -:- XL' WHERE sku = '80724';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80725';
UPDATE product_product SET short_description = 'Black/Pink -:- S' WHERE sku = '80584';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80630';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80631';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80634';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80636';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80637';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80638';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80639';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80641';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80643';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80645';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80648';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80650';
UPDATE product_product SET short_description = 'Pink/White -:- M->Pink/White -:- L' WHERE sku = '80652';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80653';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80654';
UPDATE product_product SET short_description = 'White/Pink -:- S->White/Pink -:- M->White/Pink -:- L->White/Pink -:- XL' WHERE sku = '80655';
UPDATE product_product SET short_description = 'White -:- One Size->White -:- XL' WHERE sku = '80656';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80657';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80662';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80663';
UPDATE product_product SET short_description = 'White -:- S/M->White -:- M/L->White -:- XL' WHERE sku = '80665';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80666';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80667';
UPDATE product_product SET short_description = 'Purple -:- S/M->Purple -:- M/L->Purple -:- XL' WHERE sku = '80673';
UPDATE product_product SET short_description = 'Light Blue/White -:- S/M->Light Blue/White -:- M/L->Light Blue/White -:- XL' WHERE sku = '80674';
UPDATE product_product SET short_description = 'Black/Blue -:- S/M->Black/Blue -:- M/L->Black/Blue -:- XL' WHERE sku = '80676';
UPDATE product_product SET short_description = 'Green -:- S/M->Green -:- M/L->Green -:- XL' WHERE sku = '80677';
UPDATE product_product SET short_description = 'Leopard -:- S/M->Leopard -:- M/L->Leopard -:- XL' WHERE sku = '80688';
UPDATE product_product SET short_description = 'Leopard -:- One Size->Leopard -:- XL' WHERE sku = '80690';
UPDATE product_product SET short_description = 'Camouflage -:- One Size->Camouflage -:- XL' WHERE sku = '80691';
UPDATE product_product SET short_description = 'Yellow -:- S/M->Yellow -:- M/L->Yellow -:- XL' WHERE sku = '80692';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80701';
UPDATE product_product SET short_description = 'Pink -:- One Size->Pink -:- XL' WHERE sku = '80702';
UPDATE product_product SET short_description = 'Pink -:- S/M->Pink -:- M/L->Pink -:- XL' WHERE sku = '80703';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80704';
UPDATE product_product SET short_description = 'Black/White -:- S->Black/White -:- M->Black/White -:- L->Black/White -:- XL' WHERE sku = '80705';
UPDATE product_product SET short_description = 'Black/Light Pink -:- S/M->Black/Light Pink -:- M/L->Black/Light Pink -:- XL' WHERE sku = '80708';
UPDATE product_product SET short_description = 'Black/Leopard -:- S/M->Black/Leopard -:- M/L->Black/Leopard -:- XL' WHERE sku = '80711';
UPDATE product_product SET short_description = 'Black/Pink -:- S->Black/Pink -:- M->Black/Pink -:- L->Black/Pink -:- XL' WHERE sku = '80712';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80713';
UPDATE product_product SET short_description = 'Black Lace -:- S->Black Lace -:- M->Black Lace -:- L->Black Lace -:- XL' WHERE sku = '80714';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80718';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80719';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80720';
UPDATE product_product SET short_description = 'Black/White -:- S/M->Black/White -:- M/L->Black/White -:- XL' WHERE sku = '80723';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80726';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80727';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80738';
UPDATE product_product SET short_description = 'Blue Green/Black -:- S->Blue Green/Black -:- M->Blue Green/Black -:- XL' WHERE sku = '80739';
UPDATE product_product SET short_description = 'Aqua/Black -:- S/M->Aqua/Black -:- M/L->Aqua/Black -:- XL' WHERE sku = '80740';
UPDATE product_product SET short_description = 'Turquoise/Black -:- S->Turquoise/Black -:- M->Turquoise/Black -:- XL' WHERE sku = '80741';
UPDATE product_product SET short_description = 'Black/Nude -:- S/M->Black/Nude -:- M/L->Black/Nude -:- XL' WHERE sku = '80742';
UPDATE product_product SET short_description = 'Black/Soft Pink -:- S->Black/Soft Pink -:- M->Black/Soft Pink -:- L->Black/Soft Pink -:- XL' WHERE sku = '80743';
UPDATE product_product SET short_description = 'Aqua Blue/Black Lace -:- S/M->Aqua Blue/Black Lace -:- M/L->Aqua Blue/Black Lace -:- XL' WHERE sku = '80744';
UPDATE product_product SET short_description = 'Pink Satin -:- S->Pink Satin -:- M->Pink Satin -:- L->Pink Satin -:- XL' WHERE sku = '80745';
UPDATE product_product SET short_description = 'Black Lace/Red Satin Ribbon -:- S->Black Lace/Red Satin Ribbon -:- M->Black Lace/Red Satin Ribbon -:- L->Black Lace/Red Satin Ribbon -:- XL' WHERE sku = '80746';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80514';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80515';
UPDATE product_product SET short_description = 'Black -:- S/M->Black -:- M/L->Black -:- XL' WHERE sku = '80531';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80536';
UPDATE product_product SET short_description = 'White/Green -:- S/M->White/Greene -:- M/L->White/Green -:- XL' WHERE sku = '80611';
UPDATE product_product SET short_description = 'Red Wine/Black -:- S->Red Wine/Black -:- M->Red Wine/Black -:- L->Red Wine/Black -:- XL' WHERE sku = '80730';
UPDATE product_product SET short_description = 'Sea Blue/Black -:- S->Sea Blue/Black -:- M->Sea Blue/Blacke -:- L->Sea Blue/Black -:- XL' WHERE sku = '80731';
UPDATE product_product SET short_description = 'Pink Rose -:- S->Pink Rose -:- M->Pink Rose -:- L->Pink Rose -:- XL' WHERE sku = '80732';
UPDATE product_product SET short_description = 'Pink Rose -:- S->Pink Rose -:- M->Pink Rose -:- L->Pink Rose -:- XL' WHERE sku = '80733';
UPDATE product_product SET short_description = 'Rose -:- S/M->Rose -:- M/L->Rose -:- XL' WHERE sku = '80734';
UPDATE product_product SET short_description = 'Red -:- S/M->Red -:- M/L->Red -:- XL' WHERE sku = '80735';
UPDATE product_product SET short_description = 'Black -:- S->Black -:- M->Black -:- L->Black -:- XL' WHERE sku = '80736';
UPDATE product_product SET short_description = 'Lipstick Pink -:- S/M->Lipstick Pink -:- M/L->Lipstick Pink -:- XL' WHERE sku = '80737';
UPDATE product_product SET short_description = 'White -:- S->White -:- M->White -:- L->White -:- XL' WHERE sku = '80625';

